/**
 * =============================================================================
 * PDF REPORT TEMPLATE
 * =============================================================================
 *
 * This file defines the visual layout of the exported PDF report.
 * It uses @react-pdf/renderer which provides React components
 * specifically for creating PDFs.
 *
 * IMPORTANT:
 * - This is NOT regular HTML/CSS — it uses its own primitives
 * - <View> = <div>, <Text> = <p>/<span>, <Page> = a page break
 * - Styles use a subset of CSS (no Tailwind here!)
 *
 * TODO (Team Member C):
 * - Add company logo to cover page
 * - Add page numbers in footer
 * - Add chart images (render charts to PNG first)
 * - Add table of contents
 * - Improve styling and brand colors
 *
 * Owner: Backend Lead (Team Member C)
 * =============================================================================
 */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { ProjectState } from "@/lib/types";
import { AGENT_CONFIGS } from "@/lib/agents/config";

// ─────────────────────────────────────────────────────────────────────────────
// STYLES
// ─────────────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  coverPage: {
    padding: 60,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  coverTitle: {
    fontSize: 36,
    fontFamily: "Helvetica-Bold",
    marginBottom: 12,
    textAlign: "center",
  },
  coverSubtitle: {
    fontSize: 16,
    color: "#666",
    marginBottom: 40,
    textAlign: "center",
  },
  coverMeta: {
    fontSize: 10,
    color: "#999",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    marginTop: 20,
    color: "#6366f1",
    borderBottomWidth: 2,
    borderBottomColor: "#6366f1",
    paddingBottom: 4,
  },
  subsectionTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    marginTop: 14,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 8,
  },
  summaryBox: {
    backgroundColor: "#f3f4f6",
    padding: 12,
    borderRadius: 4,
    marginBottom: 16,
  },
  summaryText: {
    fontSize: 11,
    fontStyle: "italic",
    color: "#4b5563",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#999",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// REPORT DOCUMENT COMPONENT
// ─────────────────────────────────────────────────────────────────────────────

interface ReportDocumentProps {
  project: ProjectState;
}

export function ReportDocument({ project }: ReportDocumentProps) {
  const { input, agents } = project;

  return (
    <Document>
      {/* ── Cover Page ─────────────────────────────────────────────────── */}
      <Page size="A4" style={styles.coverPage}>
        <Text style={styles.coverTitle}>{input.startupName}</Text>
        <Text style={styles.coverSubtitle}>
          AI-Powered Startup Analysis Report
        </Text>
        <Text style={styles.coverMeta}>
          Generated by Founders Orchestra
        </Text>
        <Text style={styles.coverMeta}>
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>

        {/* Startup idea summary */}
        <View style={{ ...styles.summaryBox, marginTop: 60 }}>
          <Text style={{ ...styles.subsectionTitle, marginTop: 0 }}>
            Startup Idea
          </Text>
          <Text style={styles.paragraph}>{input.idea}</Text>
          {input.industry && (
            <Text style={styles.paragraph}>
              Industry: {input.industry}
            </Text>
          )}
          {input.targetAudience && (
            <Text style={styles.paragraph}>
              Target: {input.targetAudience}
            </Text>
          )}
        </View>
      </Page>

      {/* ── Agent Output Pages ─────────────────────────────────────────── */}
      {Object.entries(agents).map(([agentId, output]) => {
        if (!output || output.status !== "completed") return null;
        const config = AGENT_CONFIGS[agentId as keyof typeof AGENT_CONFIGS];

        return (
          <Page key={agentId} size="A4" style={styles.page}>
            {/* Agent section title */}
            <Text style={styles.sectionTitle}>{config.name}</Text>

            {/* Summary */}
            <View style={styles.summaryBox}>
              <Text style={styles.summaryText}>{output.summary}</Text>
            </View>

            {/* Sections */}
            {output.sections.map((section, idx) => (
              <View key={idx}>
                <Text style={styles.subsectionTitle}>
                  {section.heading}
                </Text>
                <Text style={styles.paragraph}>{section.content}</Text>

                {/* TODO: Add chart images here */}
                {/* TODO: Add table rendering here */}
              </View>
            ))}

            {/* Page footer */}
            <Text style={styles.footer}>
              {input.startupName} — Founders Orchestra Report — Page{" "}
              {Object.keys(agents).indexOf(agentId) + 2}
            </Text>
          </Page>
        );
      })}
    </Document>
  );
}
