/**
 * =============================================================================
 * API ROUTE — GitHub Issues Export
 * =============================================================================
 *
 * Publishes AI-generated GitHub issues directly to a real GitHub repository
 * via the GitHub REST API.
 * =============================================================================
 */

import { NextResponse } from "next/server";

interface ExportRequestBody {
  token: string;
  owner: string;
  repo: string;
  issues: Array<{
    number: string;
    title: string;
    labels: string[];
    priority: "P1" | "P2" | "P3";
    story_points: number;
    epic: string;
  }>;
}

export async function POST(req: Request) {
  try {
    const body: ExportRequestBody = await req.json();
    const { token, owner, repo, issues } = body;

    if (!token || !owner || !repo || !issues || !Array.isArray(issues)) {
      return NextResponse.json(
        { error: "Missing required fields: token, owner, repo, or issues." },
        { status: 400 }
      );
    }

    const cleanToken = token.trim();
    const cleanOwner = owner.trim();
    const cleanRepo = repo.trim();

    const headers = {
      Authorization: `Bearer ${cleanToken}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "Founders-Orchestra-App",
    };

    // 1. Validate Repository Access
    const repoCheckRes = await fetch(
      `https://api.github.com/repos/${cleanOwner}/${cleanRepo}`,
      { headers }
    );

    if (!repoCheckRes.ok) {
      if (repoCheckRes.status === 401) {
        return NextResponse.json(
          { error: "Invalid GitHub Personal Access Token." },
          { status: 401 }
        );
      }
      if (repoCheckRes.status === 404) {
        return NextResponse.json(
          { error: `Repository '${cleanOwner}/${cleanRepo}' not found or token lacks access.` },
          { status: 404 }
        );
      }
      const errText = await repoCheckRes.text();
      return NextResponse.json(
        { error: `GitHub API error (${repoCheckRes.status}): ${errText}` },
        { status: repoCheckRes.status }
      );
    }

    // 2. Create Issues sequentially to adhere to GitHub secondary rate limits
    let createdCount = 0;
    const createdIssues: Array<{ id: number; html_url: string; title: string }> = [];

    for (const issue of issues) {
      const issueLabels = Array.from(
        new Set([
          ...(issue.labels || []),
          `priority:${issue.priority || "P2"}`,
          ...(issue.epic ? [`epic:${issue.epic}`] : []),
        ])
      );

      const issueBody = `## 🚀 Generated by Founders Orchestra
**Epic:** ${issue.epic || "Core Implementation"}
**Priority:** ${issue.priority || "P2"}
**Story Points:** ${issue.story_points || 3} sp

---
### Description
This engineering task was generated by the Engineering Manager AI agent for your startup kickoff.

*Tracked via [Founders Orchestra Workspace]*`;

      const createRes = await fetch(
        `https://api.github.com/repos/${cleanOwner}/${cleanRepo}/issues`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            title: issue.title,
            body: issueBody,
            labels: issueLabels,
          }),
        }
      );

      if (createRes.ok) {
        const data = await createRes.json();
        createdCount++;
        createdIssues.push({
          id: data.number,
          html_url: data.html_url,
          title: data.title,
        });
      }

      // Small delay between calls to prevent rate limits
      await new Promise((resolve) => setTimeout(resolve, 250));
    }

    return NextResponse.json({
      success: true,
      createdCount,
      repoUrl: `https://github.com/${cleanOwner}/${cleanRepo}/issues`,
      createdIssues,
    });
  } catch (err: any) {
    console.error("[GitHub Export Route Error]", err);
    return NextResponse.json(
      { error: err.message || "Failed to export issues to GitHub." },
      { status: 500 }
    );
  }
}
