/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * =============================================================================
 * API ROUTE — Notion Startup OS Export
 * =============================================================================
 *
 * Deploys a live Notion Startup Operating System workspace using native
 * Notion page, table, and formatting blocks.
 *
 * Owner: Backend Lead / AI Integration
 * =============================================================================
 */

import { NextResponse } from "next/server";
import { Client } from "@notionhq/client";
import { connectDB } from "@/lib/db/mongodb";
import { Project } from "@/lib/db/models/project";
import type {
  StartupAdvisorOutput,
  MarketResearchOutput,
  ProductManagerOutput,
  MarketingOutput,
  ArchitectOutput,
  EngineeringManagerOutput,
} from "@/lib/agents/schemas";

function extractPageId(input: string): string {
  const clean = input.trim();
  const match = clean.match(/([a-f0-9]{32})/i) || clean.match(/([a-f0-9-]{36})/i);
  if (match) {
    return match[1].replace(/-/g, "");
  }
  return clean.replace(/-/g, "");
}

function cell(text: string, bold = false) {
  return [
    {
      type: "text" as const,
      text: { content: text || "" },
      annotations: { bold },
    },
  ];
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { apiKey, parentPageId, projectId } = body;

    if (!apiKey || !parentPageId || !projectId) {
      return NextResponse.json(
        { error: "Missing required fields: apiKey, parentPageId, or projectId." },
        { status: 400 }
      );
    }

    const cleanKey = apiKey.trim();
    const cleanParentId = extractPageId(parentPageId);

    const notion = new Client({ auth: cleanKey });

    // 1. Fetch Project Data from Database
    await connectDB();
    const project = await Project.findById(projectId);
    if (!project) {
      return NextResponse.json({ error: "Project not found in database." }, { status: 404 });
    }

    const startupName = project.input?.startupName || "My Startup";
    const agents = project.agents || {};

    const advisor = agents["startup-advisor"] as StartupAdvisorOutput | undefined;
    const market = agents["market-research"] as MarketResearchOutput | undefined;
    const pm = agents["product-manager"] as ProductManagerOutput | undefined;
    const marketing = agents["marketing"] as MarketingOutput | undefined;
    const architect = agents["architect"] as ArchitectOutput | undefined;
    const eng = agents["engineering-manager"] as EngineeringManagerOutput | undefined;

    // 2. Create Parent Page in Notion
    const parentPage = await notion.pages.create({
      parent: { page_id: cleanParentId },
      icon: { type: "emoji", emoji: "🚀" },
      properties: {
        title: {
          title: [
            {
              text: { content: `${startupName} — Live AI Operating System` },
            },
          ],
        },
      },
    });

    const rootPageId = parentPage.id;

    // 3. Append Callout Summary & Key Highlights to Parent Page
    const pmfVal = advisor?.pmf_score?.score !== undefined
      ? `${advisor.pmf_score.score > 0 && advisor.pmf_score.score <= 10 ? advisor.pmf_score.score * 10 : advisor.pmf_score.score}/100`
      : "N/A";
    const tamVal = advisor?.tam?.value || market?.market_sizing?.tam?.value || "N/A";
    const riskVal = advisor?.risk_level || "Medium";

    await notion.blocks.children.append({
      block_id: rootPageId,
      children: [
        {
          object: "block",
          type: "callout",
          callout: {
            icon: { type: "emoji", emoji: "⚡" },
            color: "purple_background",
            rich_text: [
              {
                text: {
                  content: `Startup Intelligence Briefing\nPMF Signal: ${pmfVal}  |  TAM Valuation: ${tamVal}  |  Risk Rating: ${riskVal}\n\n`,
                },
                annotations: { bold: true },
              },
              {
                text: {
                  content: advisor?.validation_summary || market?.summary || "Generated by Founders Orchestra Multi-Agent Platform.",
                },
              },
            ],
          },
        },
        {
          object: "block",
          type: "heading_2",
          heading_2: {
            rich_text: [{ text: { content: "📋 Operational Workspace Modules" } }],
          },
        },
      ],
    });

    // 4. Create Competitor Intelligence Sub-Page with native Table block
    if (market?.competitors && market.competitors.length > 0) {
      const compRows = market.competitors.map((comp) => ({
        object: "block" as const,
        type: "table_row" as const,
        table_row: {
          cells: [
            cell(comp.name, true),
            cell(`${comp.scores?.ai_capability || 75}/100`),
            cell(`${comp.scores?.personalization || 70}/100`),
            cell(comp.price_per_month || "Freemium"),
            cell((comp.threat_level || "medium").toUpperCase()),
          ],
        },
      }));

      await notion.pages.create({
        parent: { page_id: rootPageId },
        icon: { type: "emoji", emoji: "🎯" },
        properties: { title: { title: [{ text: { content: "Competitor Intelligence Matrix" } }] } },
        children: [
          {
            object: "block",
            type: "table",
            table: {
              table_width: 5,
              has_column_header: true,
              has_row_header: false,
              children: [
                {
                  object: "block",
                  type: "table_row",
                  table_row: {
                    cells: [
                      cell("Company", true),
                      cell("AI Capability", true),
                      cell("Personalization", true),
                      cell("Pricing/mo", true),
                      cell("Threat Level", true),
                    ],
                  },
                },
                ...compRows,
              ],
            },
          },
        ],
      });
    }

    // 5. Create Sprint Execution Roadmap Sub-Page with native Table block
    if (eng?.sprint_plan || eng?.github_issues) {
      const taskRows: any[] = [];
      const phases = eng.sprint_plan?.phases || [];

      if (phases.length > 0) {
        for (const phase of phases) {
          const pName = `Phase ${phase.phase_number || 1}: ${phase.name}`;
          for (const taskStr of phase.tasks || []) {
            taskRows.push({
              object: "block",
              type: "table_row",
              table_row: {
                cells: [
                  cell(taskStr, true),
                  cell(pName),
                  cell("P2"),
                  cell("3 sp"),
                ],
              },
            });
          }
        }
      } else if (eng.github_issues) {
        for (const issue of eng.github_issues) {
          taskRows.push({
            object: "block",
            type: "table_row",
            table_row: {
              cells: [
                cell(issue.title, true),
                cell("Phase 1"),
                cell(issue.priority || "P2"),
                cell(`${issue.story_points || 3} sp`),
              ],
            },
          });
        }
      }

      await notion.pages.create({
        parent: { page_id: rootPageId },
        icon: { type: "emoji", emoji: "⚡" },
        properties: { title: { title: [{ text: { content: "Sprint Execution Roadmap" } }] } },
        children: [
          {
            object: "block",
            type: "table",
            table: {
              table_width: 4,
              has_column_header: true,
              has_row_header: false,
              children: [
                {
                  object: "block",
                  type: "table_row",
                  table_row: {
                    cells: [
                      cell("Task Description", true),
                      cell("Milestone Phase", true),
                      cell("Priority", true),
                      cell("Story Points", true),
                    ],
                  },
                },
                ...taskRows,
              ],
            },
          },
        ],
      });
    }

    // 6. Create Child Sub-Pages for PRD, Marketing, and Architecture
    if (pm) {
      await notion.pages.create({
        parent: { page_id: rootPageId },
        icon: { type: "emoji", emoji: "📝" },
        properties: { title: { title: [{ text: { content: "Product Blueprint & PRD" } }] } },
        children: [
          { object: "block", type: "heading_2", heading_2: { rich_text: [{ text: { content: "Product Vision" } }] } },
          { object: "block", type: "paragraph", paragraph: { rich_text: [{ text: { content: pm.product_vision || pm.summary } }] } },
          { object: "block", type: "heading_2", heading_2: { rich_text: [{ text: { content: "User Stories" } }] } },
          ...(pm.user_stories || []).map((story) => ({
            object: "block" as const,
            type: "bulleted_list_item" as const,
            bulleted_list_item: {
              rich_text: [
                { text: { content: `${story.id}: ` }, annotations: { bold: true } },
                { text: { content: `${story.text} [${story.priority}]` } },
              ],
            },
          })),
        ],
      });
    }

    if (marketing) {
      await notion.pages.create({
        parent: { page_id: rootPageId },
        icon: { type: "emoji", emoji: "📢" },
        properties: { title: { title: [{ text: { content: "Marketing Launch Kit" } }] } },
        children: [
          { object: "block", type: "heading_2", heading_2: { rich_text: [{ text: { content: "Landing Page Copy" } }] } },
          { object: "block", type: "callout", callout: { rich_text: [{ text: { content: `${marketing.landing_page?.headline}\n\n${marketing.landing_page?.subheadline}` } }] } },
          { object: "block", type: "heading_2", heading_2: { rich_text: [{ text: { content: "LinkedIn Launch Post" } }] } },
          { object: "block", type: "paragraph", paragraph: { rich_text: [{ text: { content: marketing.linkedin_post?.content || "" } }] } },
        ],
      });
    }

    if (architect?.database_schema) {
      const sqlCode = architect.database_schema.map((tbl) => {
        const cols = (tbl.columns || []).map(c => `  ${c.name} ${c.type}${c.is_pk ? " PRIMARY KEY" : ""}`).join(",\n");
        return `CREATE TABLE ${tbl.table} (\n${cols}\n);`;
      }).join("\n\n");

      await notion.pages.create({
        parent: { page_id: rootPageId },
        icon: { type: "emoji", emoji: "📐" },
        properties: { title: { title: [{ text: { content: "Database System Architecture" } }] } },
        children: [
          { object: "block", type: "heading_2", heading_2: { rich_text: [{ text: { content: "SQL Relational Schema Blueprint" } }] } },
          { object: "block", type: "code", code: { rich_text: [{ text: { content: sqlCode } }], language: "sql" } },
        ],
      });
    }

    const pageUrl = (parentPage as any).url || `https://notion.so/${rootPageId.replace(/-/g, "")}`;

    return NextResponse.json({
      success: true,
      workspaceUrl: pageUrl,
    });
  } catch (err: any) {
    console.error("[Notion Export Error]", err);
    return NextResponse.json(
      { error: err.message || "Failed to deploy Notion Startup OS workspace." },
      { status: 500 }
    );
  }
}
